# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
    # specify the version you desire here
      - image: circleci/php:7.4-browsers
      - image: circleci/postgres:12-alpine

    steps:
      - checkout
      - run: sudo apt-get install postgresql-client libpq-dev
      - run: sudo docker-php-ext-install pgsql
      - run: sudo docker-php-ext-configure pgsql -with-pgsql=/usr/local/pgsql
    # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "composer.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: composer install -n --prefer-dist

      - save_cache:
          paths:
          - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}

      - run: vendor/bin/phpstan analyse src --level 5
      - run: vendor/bin/phpunit -c phpunit-unit.xml --coverage-clover=coverage.xml
      - run: bash <(curl -s https://codecov.io/bash)
      - run: PHPUNIT_RDB_PG_DBNAME=postgres PHPUNIT_RDB_PG_USER=postgres vendor/bin/phpunit -c phpunit-db.xml
